name: 'Analogicus Janeway GDS Action'
description: 'This action generates a GDS'

runs:
    using: 'composite'
    steps:
      - name: Checkout dependencies
        shell: bash
        run: |
          python3 -m pip install cicconf
          cicconf --rundir ../ --config config.yaml clone --https
      - name: Read info
        id: info
        shell: bash
        run: |
          python3 ${GITHUB_ACTION_PATH}/../yamlToVariables info.yaml --paths "library,cell" >> "$GITHUB_OUTPUT"
      - name: Check for Cell
        shell: bash
        env:
          CELL: ${{ steps.info.outputs.cell }}
          LIBRARY: ${{ steps.info.outputs.library }}
        run: |
          bash ${GITHUB_ACTION_PATH}/../checkForSch
          bash ${GITHUB_ACTION_PATH}/../checkForLay
      - name: Run GDS
        shell: bash
        env:
          CELL: ${{ steps.info.outputs.cell }}
          LIBRARY: ${{ steps.info.outputs.library }}

        run: |
          export PDK_ROOT=/opt/pdk/share/pdk
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "/opt/eda/bin" >> $GITHUB_PATH
          cd work
          make gds CELL=$CELL LIB=$LIBRARY
          ls -l gds
          cat gds/${CELL}.log >> $GITHUB_STEP_SUMMARY
          test -s gds/${CELL}.gds || exit 1;
      - name: Archive GDS
        uses: actions/upload-artifact@v4
        with:
          name: gds
          path: |
            work/gds/${{ inputs.cell }}.gds
            work/gds/${{ inputs.cell }}.log
