name: 'Analogicus Janeway Simulation action'
description: 'This action runs a simulation, and posts to summary'


inputs:
  makestr:
    description: 'make <makestr>'
    required: true
    type: string
  folder:
    description: 'Where to run make'
    required: true
    type: string


runs:
    using: 'composite'
    steps:
      - name: Run simulation
        shell: bash
        env:
          MAKSTR: ${{ inputs.makstr }}
          FOLDER: ${{ inputs.folder }}

        run: |
          export PDK_ROOT=/opt/pdk/share/pdk
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "/opt/eda/bin" >> $GITHUB_PATH
          cd $FOLDER
          make $MAKESTR | tee "$GITHUB_SUMMARY"
      - name: Archive simulation results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            ${{ inputs.folder }}/results
