name: 'Analogicus Janeway Simulation action'
description: 'This action runs a simulation, and posts to summary'

runs:
    using: 'composite'
    steps:
      - name: Checkout dependencies
        shell: bash
        run: |
          python3 -m pip install cicconf cicsim
          cicconf --rundir ../ --config config.yaml clone --https
      - name: Run simulation
        shell: bash
        run: |
          echo "set ng_nomodcheck \nset skywaterpdk \n set num_threads=8 \n option noinit \n option klu \n optran 0 0 0 100p 2n 0 \n option opts" > $HOME/.spiceinit
          export PDK_ROOT=/opt/pdk/share/pdk
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "/opt/eda/bin" >> $GITHUB_PATH
          python3 tech/script/runsim --info info.yaml | tee "$GITHUB_STEP_SUMMARY"
      - name: Archive simulation results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            ${{ inputs.folder }}/results
