name: 'Analogicus Janeway Documentation Action'
description: 'This action generates jekyll docs'
branding:
  color: purple
  icon: layers

runs:
    using: 'composite'
    steps:
      - name: Checkout dependencies
        shell: bash
        run: |
          python3 -m pip install cicconf

          echo -e "\nGDS2glTF:\n  remote: git@github.com:wulffern/GDS2glTF.git\n  revision: main" >> config.yaml

          cicconf --rundir ../ --config config.yaml clone --https

          python3 -m pip install -r ../GDS2glTF/requirements.txt
      - name: Install cicsim
        shell: bash
        run:  python3 -m pip install cicsim
      - name: Run docs
        shell: bash
        run: |
          export PDK_ROOT=/opt/pdk/share/pdk
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "/opt/eda/bin" >> $GITHUB_PATH
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/eda/lib
          git config --global --add safe.directory `pwd`
          export PATH=/opt/eda/bin:$HOME/.local/bin:$PATH
          bash  ${GITHUB_ACTION_PATH}/gendoc
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
