#!/bin/bash



if [[ -z "${GITHUB_ACTION_PATH}" ]]; then
    export DOC_SCRIPT_PATH=`dirname $(realpath $0)`
else
    echo "INFO: found github path"
    export DOC_SCRIPT_PATH=${GITHUB_ACTION_PATH}

fi

echo "INFO: Using scripts in ${DOC_SCRIPT_PATH}"

test -d docs ||  cicsim template --dname docs ${DOC_SCRIPT_PATH}/template.yaml info.yaml
cd work
python3 ${DOC_SCRIPT_PATH}/makeMarkdown --info ../info.yaml
cd ..
test -d media && cp -r media docs/
test -d documents/* && cp -r documents/* docs/

exit 0
