name: 'Analogicus Janeway Read library'
description: 'Read library and cell from info.yaml'

#outputs:
#      library: ${{ steps.library.outputs.LIBRARY }}
#      cell: ${{ steps.cell.outputs.CELL }}

runs:
    using: 'composite'
    steps:
      - name: Read library
        shell: bash
        run: |
          ls -l
          cat info.yaml
          python3 ${GITHUB_ACTION_PATH}/yamlToVariables info.yaml
          python3 ${GITHUB_ACTION_PATH}/yamlToVariables info.yaml|xargs echo  >> "$GITHUB_OUTPUT"
