name: 'Analogicus Janeway Read library'
description: 'Read library and cell from info.yaml'

#outputs:
#      library: ${{ steps.library.outputs.LIBRARY }}
#      cell: ${{ steps.cell.outputs.CELL }}

runs:
    using: 'composite'
    steps:
      - name: Read library
        shell: bash
        run: |
          python3 -m ${GITHUB_ACTION_PATH}/yamlToVariables info.yaml > $GITHUB_OUTPUT
