#!/usr/bin/env python3

import re
import click
import yaml
import os

@click.command()
@click.argument("yfile")
def cli(yfile):
    with open(yfile) as fi:
        with open(os.environ['GITHUB_OUTPUT'],'a') as fh:
            obj = yaml.safe_load(fi)
            for o in obj:
                v = obj[o]
                if(type(v) is list):
                    continue
                if(type(v) is dict):
                    continue

                ss = "%s=%s\n"%(o.upper(),v)
                if(re.search(r"\s",v)):
                    ss = "%s=\"%s\"\n"%(o.upper(),v)

                fh.write(ss)




if(__name__ == '__main__'):
    cli()
